name: Meta Ad A/B Evaluation

on:
  schedule:
    - cron: '0 22 * * *'  # JST 7:00（UTC時間で設定）
  workflow_dispatch:       # 手動実行もOK

jobs:
  abtest-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run A/B Evaluation Script
        run: python meta_abtest_runner.py
        env:
          ACCESS_TOKEN: ${{ secrets.META_ACCESS_TOKEN }}
          ACCOUNT_ID: "act_1410377143077190"  # ← 対象アカウントIDをここにセット
