name: Test Python Setup

on:
  workflow_dispatch:

jobs:
  test-python:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Check Python
        run: python -c "print('✅ Python is working!')"
